(function() {var implementors = {};
implementors["bumpalo"] = [{text:"impl&lt;'bump, T:&nbsp;'bump&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"bumpalo/collections/vec/struct.Vec.html\" title=\"struct bumpalo::collections::vec::Vec\">Vec</a>&lt;'bump, T&gt;&gt; for <a class=\"struct\" href=\"bumpalo/collections/vec/struct.Vec.html\" title=\"struct bumpalo::collections::vec::Vec\">Vec</a>&lt;'bump, T&gt;",synthetic:false,types:["bumpalo::collections::vec::Vec"]},{text:"impl&lt;'bump, T:&nbsp;'bump&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a>T<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt; for <a class=\"struct\" href=\"bumpalo/collections/vec/struct.Vec.html\" title=\"struct bumpalo::collections::vec::Vec\">Vec</a>&lt;'bump, T&gt;",synthetic:false,types:["bumpalo::collections::vec::Vec"]},{text:"impl&lt;'bump&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"bumpalo/collections/string/struct.String.html\" title=\"struct bumpalo::collections::string::String\">String</a>&lt;'bump&gt;",synthetic:false,types:["bumpalo::collections::string::String"]},{text:"impl&lt;'bump&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt; for <a class=\"struct\" href=\"bumpalo/collections/string/struct.String.html\" title=\"struct bumpalo::collections::string::String\">String</a>&lt;'bump&gt;",synthetic:false,types:["bumpalo::collections::string::String"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
