(function() {var implementors = {};
implementors["plotters"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/coord/struct.Shift.html\" title=\"struct plotters::coord::Shift\">Shift</a>",synthetic:false,types:["plotters::coord::Shift"]},{text:"impl&lt;DB:&nbsp;<a class=\"trait\" href=\"plotters/drawing/backend/trait.DrawingBackend.html\" title=\"trait plotters::drawing::backend::DrawingBackend\">DrawingBackend</a>, CT:&nbsp;<a class=\"trait\" href=\"plotters/coord/trait.CoordTranslate.html\" title=\"trait plotters::coord::CoordTranslate\">CoordTranslate</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/drawing/struct.DrawingArea.html\" title=\"struct plotters::drawing::DrawingArea\">DrawingArea</a>&lt;DB, CT&gt;",synthetic:false,types:["plotters::drawing::area::DrawingArea"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/style/struct.RGBAColor.html\" title=\"struct plotters::style::RGBAColor\">RGBAColor</a>",synthetic:false,types:["plotters::style::color::RGBAColor"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"plotters/style/enum.FontTransform.html\" title=\"enum plotters::style::FontTransform\">FontTransform</a>",synthetic:false,types:["plotters::style::font::font_desc::FontTransform"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/style/struct.FontDesc.html\" title=\"struct plotters::style::FontDesc\">FontDesc</a>&lt;'a&gt;",synthetic:false,types:["plotters::style::font::font_desc::FontDesc"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/style/struct.TextStyle.html\" title=\"struct plotters::style::TextStyle\">TextStyle</a>&lt;'a&gt;",synthetic:false,types:["plotters::style::TextStyle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plotters/style/struct.ShapeStyle.html\" title=\"struct plotters::style::ShapeStyle\">ShapeStyle</a>",synthetic:false,types:["plotters::style::ShapeStyle"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
